AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  baby-meals-api

  Sample SAM Template for baby-meals-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3 # seconds
    MemorySize: 256 # MB

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      DefinitionBody: !Transform
        Name: AWS::Include
        Parameters:
          Location: openapi/v1.yaml

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "HTTP API endpoint URL for HelloWorld function (dev stage)"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev/hello/"

  HelloWorldFunctionArn:
    Description: "HelloWorld Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionRoleArn:
    Description: "IAM Role ARN for HelloWorld function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
